"""
Story state machine domain.

The set of legal story states is fixed by the spec (section 4.3) and
must be enforced at the schema layer so that no other surface (a stray
script, a future migration, an MCP tool) can write a value the rest of
the system can't interpret.
"""

import pytest
from sqlalchemy import text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from kanbaroo_core import StoryState, models


def test_story_state_enum_values_match_spec() -> None:
    """
    The Python enum carries exactly the values listed in spec section
    4.3, in the documented lifecycle order.
    """
    assert [s.value for s in StoryState] == [
        "backlog",
        "todo",
        "in_progress",
        "in_review",
        "done",
    ]


def test_default_state_is_backlog(session: Session) -> None:
    """
    Stories enter the world in the ``backlog`` state.
    """
    workspace = models.Workspace(key="KAN", name="K")
    session.add(workspace)
    session.flush()
    story = models.Story(workspace_id=workspace.id, human_id="KAN-1", title="S")
    session.add(story)
    session.commit()
    assert story.state == StoryState.BACKLOG


def test_invalid_state_value_is_rejected(session: Session) -> None:
    """
    Inserting an out-of-domain ``state`` value via raw SQL fails the
    CHECK constraint generated by the Enum column.
    """
    workspace = models.Workspace(key="KAN", name="K")
    session.add(workspace)
    session.commit()

    with pytest.raises(IntegrityError):
        session.execute(
            text(
                """
                INSERT INTO stories (
                    id, workspace_id, human_id, title,
                    priority, state, created_at, updated_at, version
                ) VALUES (
                    :id, :wid, :hid, :title,
                    'none', 'on_fire', :now, :now, 1
                )
                """
            ),
            {
                "id": "11111111-1111-7000-8000-111111111111",
                "wid": workspace.id,
                "hid": "KAN-99",
                "title": "bad",
                "now": "2026-04-17T00:00:00Z",
            },
        )
        session.commit()
    session.rollback()
